### ISSUE TITLE
Can't download metadata, 500 error

### ISSUE THREAD

**Issue by jacob-Iuo** [EBI-Metagenomics/emg-toolkit#16]
I am trying to download study metadata and have a list of all the study secondary IDs in the form, ERP###### or SRP######. 
When I execute the following commmand to get data from study ERP001736, I see the following error. 

mg-toolkit -d original_metadata -a ERP001736                           
DEBUG: Accession ERP001736
DEBUG: Starting new HTTPS connection (1): www.ebi.ac.uk:443
DEBUG: https://www.ebi.ac.uk:443 "GET /ena/portal/api/search?result=read_run&query=study_accession%3DERP001736+OR+secondary_study_accession%3DERP001736&fields=run_accession%2Csecondary_sample_accession%2Csample_accession%2Cdepth&format=json HTTP/1.1" 500 10633
ERROR: Error decoding ENA sample_metadata response for accession: ERP001736

I was able to execute the same command a few days ago and it seemed to work, generating a .csv file of useful metadata. I have replicated my workflow the other day step by step, and have no idea what the problem is now. Feel free to let me know if this is a temporary server-side issue, or if there is any other command I can try.

**Comment by mberacochea** [comment]
Hi Jacob,

Thank you for reporting this issue. It is indeed a temporary server-side issue.

I'm closing this ticket now, please feel free to contact us if you need help.

Cheers
