### ISSUE TITLE
emg-toolkit as a python method

### ISSUE THREAD

**Issue by matinnuhamunada** [EBI-Metagenomics/emg-toolkit#24]
Hi,

Awesome work here!

I would like to know how I can use emg-toolkit as a python method, such as:

```
from mg_toolkit import original_metadata
original_metadata('ERP001736')
```

Sorry if I missed this in the documentation.

Best regards,
Matin N.

**Comment by SandyRogers** [comment]
Hi @matinnuhamunada 
You can use import the `mg_toolkit` helper classes and use their methods from within your python scripts like so:
```python
from mg_toolkit.metadata import OriginalMetadata
erp001736 = OriginalMetadata('ERP001736')
erp001736.fetch_metadata()
```
Thanks for using the toolkit!

**Comment by matinnuhamunada** [comment]
Thanks a lot @SandyRogers !

It might be useful for some users to have this example in the Readme file.

**Comment by SandyRogers** [comment]
No problem, I've added that example now. 
The toolkit's internals (e.g. those class names and their argument lists) might well change over time. So, especially in your case where you're relying on that being stable, I'd suggest locking the version you're using. E.g. `mg-toolkit==0.10.0` in your `requirements.txt`.
