### ISSUE TITLE
How to download .fna files of all MAGs from four species catalogues in MGnify database?

### ISSUE THREAD

**Issue by yazhinia** [EBI-Metagenomics/emg-toolkit#28]
Hi,
   I am trying to download all genomic fasta files of MAGs obtained for four species catalogues (cow-rumen, human gut, human oral and marine). However, I could find a way from the given instructions to proceed with the task. Could you let me know the precise command for retrieving the fasta files.

Thanks very much in advance for the help.

**Comment by mberacochea** [comment]
Hi @yazhinia 

Thank you for contacting us. At the moment, the toolkit doesn't support the genomes resources.

The best way to download the fasta files for the catalogue is to use the [FTP server ](https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_genomes/).

Cheers

**Comment by yazhinia** [comment]
Thank you for the suggestion.

**Comment by mberacochea** [comment]
No problem, let me know if you need more help.
