### ISSUE TITLE
bulk download metadata

### ISSUE THREAD

**Issue by snayfach** [EBI-Metagenomics/emg-toolkit#29]
I see that the emg-toolkit can be used to download metadata for an individual study.  Is there a way to bulk download metadata for metagenomes from all studies?

**Comment by mberacochea** [comment]
Hi @snayfach 

The toolkit doesn't support that ATM. I would be possible to do that using the [ENA API](https://ena-docs.readthedocs.io/en/latest/retrieval/programmatic-access.html)

Cheers

**Comment by snayfach** [comment]
Do you know what the API command would be to get all metadata? If not, no worries and you can close the issue.

**Comment by mberacochea** [comment]
Hi, 

This endpoint -> https://www.ebi.ac.uk/ena/browser/api/#/ENA_Browser_Data_API/getXmlPostUsingPOST should do the trick.

Example:
```curl
curl -X POST "https://www.ebi.ac.uk/ena/browser/api/xml?accessions=ERP001736&accessions=ERP009703" -H  "accept: application/xml"
```

Cheers
