### ISSUE TITLE
Overwrites already downloaded data.

### ISSUE THREAD

**Issue by casperp** [EBI-Metagenomics/emg-toolkit#5]
My bulk_download stopped because of a HTPP ERROR 500.
 ```urllib.error.HTTPError: HTTP Error 500: Internal Server Error```
    
But when i restart the download with the same command it overwrites the already existing data. The download already took 30 minutes and wasn't even half way. 

Is it possible that the code first checks if there are already data from a failed download and skips these while downloading ?
    
Command i used to download : 
```bash mg-toolkit bulk_download -a  MGYS00001225 -g taxonomic_annotations```

Versions:

- python:3.6.7 conda-forge
- mg-toolkit:0.6.4

**Comment by mscheremetjew** [comment]
@casperp Thanks for reporting this. This feature is already on our todo list. It makes absolutely sense to get this in.

**Comment by adnbps2** [comment]
Any updates? I have the same problem: the download won't finish, but it restarts whenever I try to resume the download. This makes it impossible to download the full dataset using mg-toolkit.

**Comment by mberacochea** [comment]
Thank you @adnbps2 for contacting us. Unfortunately we haven't implemented this yet. 

Could you please let me know what were you trying to download?.

**Comment by mberacochea** [comment]
There is a new version available that will help with this problem. The new version doesn't re-download the same files, it's safe to retry. We have also added a retry mechanism within the toolkit.

The version is 0.7.0 and it's available in pypi.
