### ISSUE TITLE
mg-toolkit for confidential MGnify study

### ISSUE THREAD

**Issue by jmcelh** [EBI-Metagenomics/emg-toolkit#6]
Dear Ola, 

I would like to try out the mg-toolkit for retrieving the metadata etc. for our team's study, ERP116156, (I am following the tutorials we learnt at EMBL metagenomics bioinformatics 2018) but receive a traceback error (please see attached metadata_error.txt) when trying the command: 

$ mg-toolkit original_metadata -a ERP116156

With the bulk download command the result is no retrieved files but otherwise a standard looking output (please see bulk.txt attached)

I suspect that this might be due to my study being listed as confidential at present (the command appears to work fine on a public study), if this is the case, might there be a workaround (asides from making it public just yet)?

Any advice would be most appreciated.

Best wishes,

James

P.S. I am not sure if this constitutes an issue with the package per se and apologize if this is not the forum for such an post (I am new to github).

[metadata_error.txt](https://github.com/EBI-Metagenomics/emg-toolkit/files/3693391/metadata_error.txt)
[bulk.txt](https://github.com/EBI-Metagenomics/emg-toolkit/files/3693405/bulk.txt)

**Comment by lambros-f** [comment]
Hey jmcelh

Did you ever figure out what the error is with this?

I am having the same issue but for public studies

**Comment by mberacochea** [comment]
Keep in mind that the toolkit doesn't support private (confidential) data sets at the moment . I've created a ticket to support private data sets https://github.com/EBI-Metagenomics/emg-toolkit/issues/10 but I can't provide an ETA.

There is a new version available that fixes this problem. Thank you for reporting the bug.
